--- #YAML:1.0
name:                Acme-ChuckNorris
version:             0.1
abstract:            Perl prefers to code in Chuck Norris
license:             ~
author:              
    - Daniel Muey <http://drmuey.com/cpan_contact.pl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Acme::EyeDrops:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
